version: '3.0'
services:
  
  service:

    container_name: ${COMPOSE_PROJECT_NAME}-service
    
    build:
      context: ./bin/myedgeapp/${BUILD_ARCH}

    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
    
    ports:
    - 80:80/tcp
    - 433:433/tcp
    
    restart: always
    
    volumes:
    - ./config/traefik.toml:/etc/traefik/traefik.toml
    - ./config/traefik_dynamic.toml:/etc/traefik/traefik_dynamic.toml
