[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$bND9Kod2$E2on/Km6iD0wkYGG/AXug1"
  ]

[http.routers.api]
  rule = "Host(`traefik-monitor.myedge.app`)"
  entrypoints = ["web"]
  middlewares = ["simpleAuth"]
  service = "api@internal"

# Dynamic configuration for each edgebox and their hostnames is defined dynamically via etcd.
